% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Analysis of STAT184 Topics},
  pdfauthor={Eric Best},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Analysis of STAT184 Topics}
\author{Eric Best}
\date{2023-11-29}

\begin{document}
\maketitle

\hypertarget{foreword}{%
\subsubsection{Foreword}\label{foreword}}

In this document, we will examine some code, datasets, and
visualizations related to STAT184. There are three sections: a
discussion on the Collaz Conjecture, an investigation on the physical
properties of Diamonds, and a summary of what we have learned in STAT184
so far.

\hypertarget{part-1-the-collatz-conjecture}{%
\subsubsection{Part 1: The Collatz
Conjecture}\label{part-1-the-collatz-conjecture}}

\hypertarget{what-is-the-collatz-conjecture}{%
\paragraph{What is the Collatz
Conjecture?}\label{what-is-the-collatz-conjecture}}

The Collatz Conjecture was introduced by Lothar Collatz. The conjecture
stipulates that these operations will eventually reduce any positive
integer to 1. We can define this as a piece-wise function, with \(n\) as
a positive integer:

\[
    f(n) =
    \begin{cases}
        \frac{n}{2} & \text{if $n$ is even} \\
        3n + 1 & \text{if $n$ is odd} \\
        STOP & \text{if $n$ = 1}
    \end{cases}
\]

\hypertarget{coding-the-conjecture}{%
\paragraph{Coding the Conjecture}\label{coding-the-conjecture}}

We've made R Code for a recursive implementation of the Conjecture. That
is, the function will repeatedly call itself to eventually reduce \(n\)
to 1. We will record the ``Stopping Points'', which are positive
integers that state how many times the function is run to reduce \(n\)
to 1.

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# We are including this code to demonstrate how the Collatz Conjecture works.}

\DocumentationTok{\#\# Function accepts a positive integer n}
\NormalTok{runCollatz }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(integerN)                          }
\NormalTok{\{}
\DocumentationTok{\#\# Stop algorithm if argument is less than or equal to 0}
  \ControlFlowTok{if}\NormalTok{ (integerN }\SpecialCharTok{\textless{}=} \DecValTok{0}\NormalTok{)                                      }
\NormalTok{  \{}
    \FunctionTok{stop}\NormalTok{(}\StringTok{"Must be a positive integer"}\NormalTok{)}
\NormalTok{  \}}
  
\DocumentationTok{\#\# Create an integer to store Stopping Point  }
\NormalTok{  integerStoppingPoint }\OtherTok{\textless{}{-}} \DecValTok{0}                               

  
\DocumentationTok{\#\# While n is not 1, go through the algorithm}
  \ControlFlowTok{while}\NormalTok{ (integerN }\SpecialCharTok{!=} \DecValTok{1}\NormalTok{)                                  }
\NormalTok{    \{}
\DocumentationTok{\#\# Case: n is even. Divide by two, resave into integerN}
      \ControlFlowTok{if}\NormalTok{ (integerN }\SpecialCharTok{\%\%} \DecValTok{2} \SpecialCharTok{==} \DecValTok{0}\NormalTok{)                             }
\NormalTok{      \{}
\NormalTok{        integerN }\OtherTok{\textless{}{-}}\NormalTok{ integerN }\SpecialCharTok{/} \DecValTok{2}
\NormalTok{      \}}
    
\DocumentationTok{\#\# Case: n is odd. Multiply by three and add one, resave}
      \ControlFlowTok{else}                                                
\NormalTok{      \{}
\NormalTok{        integerN }\OtherTok{\textless{}{-}} \DecValTok{3} \SpecialCharTok{*}\NormalTok{ integerN }\SpecialCharTok{+} \DecValTok{1}
\NormalTok{      \}}
\DocumentationTok{\#\# Accrue the stopping point counter}
\NormalTok{    integerStoppingPoint }\OtherTok{\textless{}{-}}\NormalTok{ integerStoppingPoint }\SpecialCharTok{+} \DecValTok{1}      
\NormalTok{    \}}
  \FunctionTok{return}\NormalTok{(integerStoppingPoint)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\hypertarget{histogram-for-stopping-points}{%
\paragraph{Histogram for Stopping
Points}\label{histogram-for-stopping-points}}

What kind of behavior do stopping points exhibit? Let's use a histogram
to see the distribution of this part of the Conjecture. We'll analyze
positive integers starting with 1 and going up to 10,000, recording
their respective stopping points.

\includegraphics{activity09_files/figure-latex/Chunk2: stoppingPointsHistogram-1.pdf}

\hypertarget{some-conclusions-on-the-histogram}{%
\paragraph{Some Conclusions on the
Histogram}\label{some-conclusions-on-the-histogram}}

Before we discuss this histogram, it's important to note that the
Collatz Conjecture remains unproven. Meaning, mathematicians haven't
found an integer that is not eventually reduced to 1 by the algorithm.
With that said, we can make some generalizations about stopping points,
answering Dr.~Hatfield's question:

\begin{itemize}
\item
  It seems that stopping points above \(n = 150\) start to become less
  common, with stopping points above \(n = 200\) being very uncommon.
\item
  \(n = 50\) is the most common stopping point. This is a right-skewed
  distribution, so we know that the stopping point mode should be around
  that value. Further, that mode should be greater than the stopping
  point mean and median.
\item
  Knowing the above, we can conclude that for larger and more immense
  input vectors, we will get the same distribution according to the Law
  of Large Numbers.
\end{itemize}

\hypertarget{part-2-investigating-diamonds}{%
\subsubsection{Part 2: Investigating
Diamonds}\label{part-2-investigating-diamonds}}

\hypertarget{discussion-on-diamonds-and-their-physical-properties}{%
\paragraph{Discussion on Diamonds and their Physical
Properties}\label{discussion-on-diamonds-and-their-physical-properties}}

There is a data set included with ggplot2 and it is called Diamonds.
It's a table of 53,940 diamond cuts, prices included, and contains
information on various physical properties and classifications for each
diamond. Here is a summary of those properties:

\begin{itemize}
\item
  \textbf{Carat}: a measurement of weight. We also have \textbf{x},
  \textbf{y}, and \textbf{z} dimensions for each diamond in millimeters.
\item
  \textbf{Cut}: the quality of the diamond's cut, ranging from Fair to
  Ideal.
\item
  \textbf{Clarity}: the measurement of a diamond's purity and rarity.
\item
  \textbf{Depth}: a percentage-based measurement from top to bottom of
  the stone.
\item
  \textbf{Table}: the facet of the diamond that appears when viewed
  face-up.
\end{itemize}

How might these properties influence the price of a diamond? We will
investigate this using data visualizations and statistical summaries.

\hypertarget{visualizations-of-the-diamonds-dataset}{%
\paragraph{Visualizations of the Diamonds
Dataset}\label{visualizations-of-the-diamonds-dataset}}

Shown below are dot plots that include 100 cases from the Diamonds
dataset, with the first (Fig. 1) concerning color and the second (Fig.
2) regarding cut:

\includegraphics{activity09_files/figure-latex/Chunk3: diamondsDotPlot1-1.pdf}

\includegraphics{activity09_files/figure-latex/Chunk4: diamondsDotPlot2-1.pdf}

\hypertarget{some-conclusions-on-the-diamonds-visualizations}{%
\paragraph{Some Conclusions on the Diamonds
Visualizations}\label{some-conclusions-on-the-diamonds-visualizations}}

First of all, let's discuss the Color and Cut properties. The less
color, the higher the value of the diamond. A colorless diamond is white
in appearance, while a near-colorless diamond will have a small yellow
tint. The Diamonds dataset only has diamonds with colors ranging from D
to J, which is what most jewelry stores sell. The D rating is thus the
most desirable for our data. For Cut, the most desirable diamonds
radiate light; put simply, they sparkle the most. Therefore, Ideal is
the most valuable Cut label. Here are some conclusions we can make about
this dataset:

\begin{itemize}
\item
  The majority of stones will fall under \$5000 USD in price and hover
  around and below 1.5 carats in weight. High carat stones tend to be
  valuable even if they are of mid-range colors. This is reflected in
  both figures. This might indicate that high-carat stones are more rare
  in nature.
\item
  There are few expensive Fair diamonds and J Color diamonds, because
  they are not as desirable. There are few D Color diamonds that are
  high in price, perhaps due to their rarity.
\item
  Even an Ideal or D Color Diamond can have a small price if is low in
  carats. It appears as if diamond buyers find Very Good to be a minimum
  standard for Cut quality.s
\item
  For both figures, we can see that the distribution appears roughly
  quadratic in appearance. If more samples are taken, this shape becomes
  obvious.
\end{itemize}

We will now use a table to display summary statistics about the Diamonds
dataset. This will allow us to examine many more cases compared to the
above visualizations. We'll consider the \(x\) values for the diamonds
in these calculations.

\begin{table}

\caption{\label{tab:Chunk5: diamondsSummary}Fig. 3: Statistical Facts for Diamond Length Values, in Millimeters}
\centering
\resizebox{\linewidth}{!}{
\fontsize{16}{18}\selectfont
\begin{tabular}[t]{lcccccclccc}
\toprule
\textcolor{black}{\textbf{Cut}} & \textcolor{black}{\textbf{Color}} & \textcolor{black}{\textbf{Minimum}} & \textcolor{black}{\textbf{1st Quartile}} & \textcolor{black}{\textbf{2nd Quartile}} & \textcolor{black}{\textbf{3rd Quartile}} & \textcolor{black}{\textbf{Maximum}} & \textcolor{black}{\textbf{Median}} & \textcolor{black}{\textbf{Mean}} & \textcolor{black}{\textbf{Standard Deviation}} & \textcolor{black}{\textbf{Count}}\\
\midrule
\textcolor{black}{\textbf{Fair}} & \textcolor{black}{\textbf{D}} & \textcolor{black}{\textbf{4.09}} & \textcolor{black}{\textbf{5.59}} & \textcolor{black}{\textbf{6.08}} & \textcolor{black}{\textbf{6.30}} & \textcolor{black}{\textbf{9.42}} & \textcolor{black}{\textbf{6.08}} & \textcolor{black}{\textbf{6.02}} & \textcolor{black}{\textbf{0.83}} & \textcolor{black}{\textbf{163}}\\
Fair & E & 3.87 & 5.28 & 6.07 & 6.35 & 8.16 & 6.07 & 5.91 & 0.83 & 224\\
Fair & F & 4.19 & 5.45 & 6.06 & 6.37 & 8.58 & 6.06 & 5.99 & 0.88 & 312\\
Fair & G & 3.87 & 5.59 & 6.13 & 6.52 & 8.75 & 6.13 & 6.19 & 0.93 & 313\\
Fair & H & 4.40 & 6.01 & 6.33 & 7.16 & 10.00 & 6.33 & 6.58 & 0.94 & 303\\
\addlinespace
Fair & I & 4.62 & 5.92 & 6.34 & 7.14 & 9.11 & 6.34 & 6.56 & 0.90 & 175\\
Fair & J & 4.24 & 6.06 & 6.49 & 7.38 & 10.74 & 6.49 & 6.75 & 1.09 & 119\\
\textcolor{black}{\textbf{Good}} & \textcolor{black}{\textbf{D}} & \textcolor{black}{\textbf{3.83}} & \textcolor{black}{\textbf{4.78}} & \textcolor{black}{\textbf{5.69}} & \textcolor{black}{\textbf{6.31}} & \textcolor{black}{\textbf{8.15}} & \textcolor{black}{\textbf{5.69}} & \textcolor{black}{\textbf{5.62}} & \textcolor{black}{\textbf{0.93}} & \textcolor{black}{\textbf{662}}\\
Good & E & 3.83 & 4.78 & 5.68 & 6.31 & 9.08 & 5.68 & 5.62 & 0.95 & 933\\
Good & F & 3.83 & 5.02 & 5.76 & 6.32 & 8.69 & 5.76 & 5.71 & 0.92 & 907\\
\addlinespace
Good & G & 3.94 & 5.05 & 6.05 & 6.38 & 8.90 & 6.05 & 5.85 & 1.02 & 871\\
Good & H & 4.04 & 5.07 & 6.11 & 6.62 & 9.44 & 6.11 & 5.97 & 1.13 & 702\\
Good & I & 4.19 & 5.56 & 6.28 & 7.21 & 9.38 & 6.28 & 6.25 & 1.22 & 522\\
Good & J & 4.22 & 5.65 & 6.44 & 7.23 & 9.32 & 6.44 & 6.38 & 1.12 & 307\\
\textcolor{black}{\textbf{Ideal}} & \textcolor{black}{\textbf{D}} & \textcolor{black}{\textbf{3.81}} & \textcolor{black}{\textbf{4.47}} & \textcolor{black}{\textbf{5.11}} & \textcolor{black}{\textbf{5.72}} & \textcolor{black}{\textbf{9.04}} & \textcolor{black}{\textbf{5.11}} & \textcolor{black}{\textbf{5.19}} & \textcolor{black}{\textbf{0.82}} & \textcolor{black}{\textbf{2834}}\\
\addlinespace
Ideal & E & 3.76 & 4.47 & 5.10 & 5.76 & 8.52 & 5.10 & 5.22 & 0.85 & 3903\\
Ideal & F & 3.90 & 4.53 & 5.23 & 6.18 & 8.67 & 5.23 & 5.41 & 0.98 & 3825\\
Ideal & G & 3.92 & 4.52 & 5.24 & 6.49 & 8.75 & 5.24 & 5.51 & 1.04 & 4883\\
Ideal & H & 3.94 & 4.57 & 5.68 & 6.68 & 9.65 & 5.68 & 5.73 & 1.17 & 3115\\
Ideal & I & 3.94 & 4.77 & 5.84 & 6.87 & 9.49 & 5.84 & 5.98 & 1.24 & 2093\\
\addlinespace
Ideal & J & 3.93 & 5.23 & 6.50 & 7.20 & 9.25 & 6.50 & 6.32 & 1.22 & 896\\
\textcolor{black}{\textbf{Premium}} & \textcolor{black}{\textbf{D}} & \textcolor{black}{\textbf{3.73}} & \textcolor{black}{\textbf{4.71}} & \textcolor{black}{\textbf{5.38}} & \textcolor{black}{\textbf{6.44}} & \textcolor{black}{\textbf{8.99}} & \textcolor{black}{\textbf{5.38}} & \textcolor{black}{\textbf{5.60}} & \textcolor{black}{\textbf{1.02}} & \textcolor{black}{\textbf{1602}}\\
Premium & E & 3.79 & 4.70 & 5.41 & 6.41 & 9.26 & 5.41 & 5.59 & 1.03 & 2337\\
Premium & F & 3.73 & 4.87 & 5.89 & 6.55 & 9.24 & 5.89 & 5.88 & 1.02 & 2331\\
Premium & G & 3.95 & 4.75 & 5.90 & 6.71 & 9.44 & 5.90 & 5.86 & 1.15 & 2924\\
\addlinespace
Premium & H & 3.96 & 5.17 & 6.48 & 7.04 & 9.44 & 6.48 & 6.25 & 1.22 & 2359\\
Premium & I & 3.97 & 5.40 & 6.74 & 7.46 & 10.14 & 6.74 & 6.49 & 1.32 & 1428\\
Premium & J & 4.22 & 6.04 & 6.92 & 7.62 & 10.02 & 6.92 & 6.81 & 1.22 & 808\\
\textcolor{black}{\textbf{Very Good}} & \textcolor{black}{\textbf{D}} & \textcolor{black}{\textbf{3.86}} & \textcolor{black}{\textbf{4.69}} & \textcolor{black}{\textbf{5.46}} & \textcolor{black}{\textbf{6.30}} & \textcolor{black}{\textbf{9.08}} & \textcolor{black}{\textbf{5.46}} & \textcolor{black}{\textbf{5.50}} & \textcolor{black}{\textbf{0.97}} & \textcolor{black}{\textbf{1513}}\\
Very Good & E & 3.74 & 4.60 & 5.33 & 6.27 & 8.65 & 5.33 & 5.43 & 1.00 & 2400\\
\addlinespace
Very Good & F & 3.84 & 4.73 & 5.69 & 6.38 & 8.64 & 5.69 & 5.61 & 1.00 & 2164\\
Very Good & G & 3.88 & 4.69 & 5.68 & 6.44 & 8.65 & 5.68 & 5.66 & 1.04 & 2299\\
Very Good & H & 3.89 & 4.96 & 6.13 & 6.76 & 9.23 & 6.13 & 5.99 & 1.15 & 1823\\
Very Good & I & 3.95 & 5.58 & 6.35 & 7.19 & 10.01 & 6.35 & 6.27 & 1.17 & 1204\\
Very Good & J & 3.94 & 5.67 & 6.56 & 7.29 & 8.89 & 6.56 & 6.46 & 1.14 & 678\\
\bottomrule
\multicolumn{11}{l}{\rule{0pt}{1em}\textit{Note: }}\\
\multicolumn{11}{l}{\rule{0pt}{1em}GGplot2 Diamonds Dataset had cases with non-positive Lengths. Above data excludes those.}\\
\multicolumn{11}{l}{\rule{0pt}{1em}\textsuperscript{1} Data displayed above rounded to two decimal places.}\\
\end{tabular}}
\end{table}

\hypertarget{looking-at-the-diamond-summary-table}{%
\paragraph{Looking at the Diamond Summary
Table}\label{looking-at-the-diamond-summary-table}}

We've made a rather large table to look at each combination of Color and
Cut in the dataset, with the most desirable combinations in bold. We can
see immediately that most diamonds aren't below 3.73 mm for their
x-value, and the maximums for each category fall at around \(x = 8.0\).
Indeed, the maximum of all categories is \(x = 10.02\). This could mean
that there is some sort of physical bounds for the sizes of diamonds
found in nature.

\hypertarget{considering-the-plots-and-table-together}{%
\paragraph{Considering the Plots and Table
Together}\label{considering-the-plots-and-table-together}}

Before, we said that certain combinations of Cut and Color might make a
diamond more valuable. First, we can say the dataset has far fewer Fair
and Good Diamonds compared to other categories. We might conclude that
there is little consumer demand for these stones compared to the supply.
It just seems that consumers prefer higher-quality cuts. The standard
deviations are not especially high for all these label combinations,
which supports the ``clustering'' of stones observed with higher random
samples.

\hypertarget{part-3-reflecting-on-stat184-thus-far}{%
\subsubsection{Part 3: Reflecting on STAT184 Thus
Far}\label{part-3-reflecting-on-stat184-thus-far}}

I'm pleased with this class so far and highly value my time spent
learning R/RStudio and coding and design techniques.

\hypertarget{learning-r-and-rstudio}{%
\paragraph{Learning R and RStudio}\label{learning-r-and-rstudio}}

With regards to learning R, I had heard of the language before, but I
thought it was similar to MATLAB or Maple. Prior to this course, I've
taken classes in C++ and Java and learned basic C on my own. It turns
out that R has a long history of improvements and feature additions over
the years, similar to the development of C in the 1970s and 1980s. This
makes R a very robust and adaptable language on its own, but there are
many projects being worked on for R that expand its usefulness, as
discussed in Activity 01.

RStudio is significantly easier to use compared to Eclipse or Visual
Studio. I have never used an Integrated Development Environment (IDE)
that was so helpful with debugging and correcting code. The included
documentation is good, although some of the examples the authors use are
rather simple. I have to admit that some of the operations in R were
confusing at first, like using the piping operator
\texttt{\%\textgreater{}\%}. I generalized the concept of piping as just
passing the argument of one function to another. Once I understood this
operation, it became a lot easier to read and interpret R code. We also
used a textbook called `Data Computing.' I found this textbook to be
dry, but at least it's open source.

\hypertarget{general-design-practices}{%
\paragraph{General Design Practices}\label{general-design-practices}}

Tidy data is the first important design principle of this class, which
means reducing a dataset to a table form that follows these three rules:
every column is a variable, every row is an observation, and all values
must have their own cell. Not every dataframe comes in a form that is
easily digestible for both a person reading the data and the RStudio
environment. These concepts were introduced in Activity \#04, and we
mastered them in Activity \#08 by tidying the messy Military Marital
Data table.

A related but equally important concept is Data Wrangling, which we
developed in Activity \#06 and Activity \#08 while finding pertinent
Diamonds data. Wrangling means finding and obtaining the data we need to
achieve a goal. Now, we know how to create a solid foundation of data
for creating good tables and visualizations.

Regarding actual graphic and element design, we have read excerpts from
Tufte and Kosslyn. To put it simply, they have provided us with advice
on creating powerful yet approachable graphics and tables. I've learned
how to create simple visualizations that still convey a lot of
information. I can now sometimes identify where R and R packages are
used in making visualizations for everyday media. The PCIP System can
also be utilized for creating visualizations and tables.

One of the most interesting topics discussed was data-scraping. We have
learned to extract data from webpages that can be tidied and wrangled
into appreciable datasets. Immediately I could see applications to
Ethical Hacking and Penetration Testing using other scraping tools
developed for R.

\hypertarget{coding-practices}{%
\paragraph{Coding Practices}\label{coding-practices}}

I learned a lot about coding guidelines and practices in this course.
Activity \#02 helped me become much more specific with nouns and verbs
for R in order to achieve a specific goal. I've sometimes had issues
deciding exactly what I want to code, and the PCIP System helps with
this. Using this framework, I have a good set of guidelines for
starting, improving, and finalizing a code project.

Activity \#05 was the most important for learning to code
visualizations, specifically using ggplot. I enjoyed investigating
additional ways to make these visualizations more engaging, like adding
footnotes. Activity \#08 was important for learning to code a data
wrangling operation. One of my favorite parts of that activity was
hand-coding dataset-specific wrangling instructions. It immediately
brought to mind the idea of creating generalized data wrangling
operations that will work on any dataset. Perhaps that objective has
already been fulfilled by independent R package developers.

\hypertarget{tying-it-all-together}{%
\paragraph{Tying it All Together}\label{tying-it-all-together}}

In the past few weeks of class, we've examined R Markdown. RMD allows us
to create reports and presentations that include code, text,
mathematical symbols, tables, and visualizations. I can see how this has
become the standard for creating scholarly documents. It is a very clean
system that helps us organize our work much better and expedites the
creation of document files. I appreciate that code chunks can have
localized properties, such as specifying a table name or instructing R
not to print error and warning messages. Suffice to say, I will be using
RMD for report management over word processors.

\newpage

\hypertarget{code-appendix}{%
\subsubsection{Code Appendix}\label{code-appendix}}

We have reproduced our code here as a reference.

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# This chunk\textquotesingle{}s code was included to provide portability to different systems.}
\DocumentationTok{\#\# We are using groundhog to load packages from a specific date.}
\DocumentationTok{\#\# We are then using \textquotesingle{}here\textquotesingle{} to load the ggplot2 dataset called diamonds.csv}
\DocumentationTok{\#\# Diamonds was obtained from: https://github.com/tidyverse/ggplot2/blob/main/data{-}raw/diamonds.csv}

\FunctionTok{library}\NormalTok{(groundhog)}
\NormalTok{groundhog.day}\OtherTok{=}\StringTok{"2023{-}11{-}26"}
\NormalTok{pkgs}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}janitor\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}dplyr\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}kableExtra\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}ggplot2\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}here\textquotesingle{}}\NormalTok{)}
\FunctionTok{groundhog.library}\NormalTok{(pkgs, groundhog.day)}
\NormalTok{knitr}\SpecialCharTok{::}\NormalTok{opts\_chunk}\SpecialCharTok{$}\FunctionTok{set}\NormalTok{(}\AttributeTok{warning =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{message =} \ConstantTok{FALSE}\NormalTok{) }
\NormalTok{csv\_path }\OtherTok{\textless{}{-}} \FunctionTok{here}\NormalTok{(}\StringTok{"diamonds.csv"}\NormalTok{)}
\NormalTok{diamonds }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(csv\_path)}
\DocumentationTok{\#\#devtools::install\_github("kupietz/kableExtra")}
\DocumentationTok{\#\# We are including this code to demonstrate how the Collatz Conjecture works.}

\DocumentationTok{\#\# Function accepts a positive integer n}
\NormalTok{runCollatz }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(integerN)                          }
\NormalTok{\{}
\DocumentationTok{\#\# Stop algorithm if argument is less than or equal to 0}
  \ControlFlowTok{if}\NormalTok{ (integerN }\SpecialCharTok{\textless{}=} \DecValTok{0}\NormalTok{)                                      }
\NormalTok{  \{}
    \FunctionTok{stop}\NormalTok{(}\StringTok{"Must be a positive integer"}\NormalTok{)}
\NormalTok{  \}}
  
\DocumentationTok{\#\# Create an integer to store Stopping Point  }
\NormalTok{  integerStoppingPoint }\OtherTok{\textless{}{-}} \DecValTok{0}                               

  
\DocumentationTok{\#\# While n is not 1, go through the algorithm}
  \ControlFlowTok{while}\NormalTok{ (integerN }\SpecialCharTok{!=} \DecValTok{1}\NormalTok{)                                  }
\NormalTok{    \{}
\DocumentationTok{\#\# Case: n is even. Divide by two, resave into integerN}
      \ControlFlowTok{if}\NormalTok{ (integerN }\SpecialCharTok{\%\%} \DecValTok{2} \SpecialCharTok{==} \DecValTok{0}\NormalTok{)                             }
\NormalTok{      \{}
\NormalTok{        integerN }\OtherTok{\textless{}{-}}\NormalTok{ integerN }\SpecialCharTok{/} \DecValTok{2}
\NormalTok{      \}}
    
\DocumentationTok{\#\# Case: n is odd. Multiply by three and add one, resave}
      \ControlFlowTok{else}                                                
\NormalTok{      \{}
\NormalTok{        integerN }\OtherTok{\textless{}{-}} \DecValTok{3} \SpecialCharTok{*}\NormalTok{ integerN }\SpecialCharTok{+} \DecValTok{1}
\NormalTok{      \}}
\DocumentationTok{\#\# Accrue the stopping point counter}
\NormalTok{    integerStoppingPoint }\OtherTok{\textless{}{-}}\NormalTok{ integerStoppingPoint }\SpecialCharTok{+} \DecValTok{1}      
\NormalTok{    \}}
  \FunctionTok{return}\NormalTok{(integerStoppingPoint)}
\NormalTok{\}}
\DocumentationTok{\#\# This code is included to show a histogram of the Collatz Stopping Points, in order to answer Dr. Hatfield\textquotesingle{}s question}

\NormalTok{intervalValues }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10000}
\DocumentationTok{\#\#Using sapply to call runCollatz on our desired list}
\NormalTok{collatzVector }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(intervalValues, runCollatz)}

\FunctionTok{hist}\NormalTok{(collatzVector, }\AttributeTok{breaks =} \DecValTok{100}\NormalTok{, }\AttributeTok{main =} \StringTok{"Collatz Conjecture Stopping Points Histogram"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"Stopping Point"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Frequency"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{activity09_files/figure-latex/codeAppendix-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# This code was included to show a dot plot of 100 diamonds and the relationship between prices, carat, and color}

\FunctionTok{library}\NormalTok{(ggplot2)}
\NormalTok{diamondsSampleDot }\OtherTok{\textless{}{-}}\NormalTok{ diamonds[}\FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(diamonds), }\DecValTok{100}\NormalTok{, }\AttributeTok{replace=}\ConstantTok{FALSE}\NormalTok{),]}

\DocumentationTok{\#\# Displaying dot plots to investigate price, carat, and diamond physical properties}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ diamondsSampleDot, }\AttributeTok{mapping =} \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ price, }\AttributeTok{y =}\NormalTok{ carat, }\AttributeTok{colour =}\NormalTok{ color) ) }\SpecialCharTok{+}
\FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{size =} \FloatTok{1.5}\NormalTok{) }\SpecialCharTok{+} 
\FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Price of Diamond, USD"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Carat of Diamond"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Fig. 1: Prices vs Carat of Diamonds by Color"}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{activity09_files/figure-latex/codeAppendix-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# This code was included to show a dot plot of 100 diamonds and the relationship between prices, carat, and cut}

\FunctionTok{library}\NormalTok{(ggplot2)}
\NormalTok{diamondsSampleDot }\OtherTok{\textless{}{-}}\NormalTok{ diamonds[}\FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(diamonds), }\DecValTok{100}\NormalTok{, }\AttributeTok{replace=}\ConstantTok{FALSE}\NormalTok{),]}

\DocumentationTok{\#\# Displaying dot plots to investigate price, carat, and diamond physical properties}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ diamondsSampleDot, }\AttributeTok{mapping =} \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ price, }\AttributeTok{y =}\NormalTok{ carat, }\AttributeTok{colour =}\NormalTok{ cut) ) }\SpecialCharTok{+}
\FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{size =} \FloatTok{1.5}\NormalTok{) }\SpecialCharTok{+} 
\FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Price of Diamond, USD"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Carat of Diamond"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Fig. 2: Prices vs Carat of Diamonds by Cut"}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{activity09_files/figure-latex/codeAppendix-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# This code was included to tidy up and display a table regarding the diamonds\textquotesingle{} physical properties}

\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}
\DocumentationTok{\#\#Data Wrangling\#\#}
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}

\NormalTok{dimensionStats }\OtherTok{\textless{}{-}}\NormalTok{ diamonds }\SpecialCharTok{\%\textgreater{}\%}                                      
  \FunctionTok{filter}\NormalTok{(x }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}                                              \DocumentationTok{\#\# Get the positive nonzero x{-}value}
  \FunctionTok{group\_by}\NormalTok{(cut, color) }\SpecialCharTok{\%\textgreater{}\%}                                              \DocumentationTok{\#\# Group by diamond cut}
  \FunctionTok{select}\NormalTok{(cut, color, x) }\SpecialCharTok{\%\textgreater{}\%}                                             \DocumentationTok{\#\# Select for cut and x{-}value}
  \FunctionTok{summarize}\NormalTok{(                                                     }\DocumentationTok{\#\# Use summarize and across like in class}
    \FunctionTok{across}\NormalTok{(}
      \AttributeTok{.cols =} \FunctionTok{where}\NormalTok{(is.numeric),}
      \AttributeTok{.fns =} \FunctionTok{list}\NormalTok{(}
        \AttributeTok{minimum =} \SpecialCharTok{\textasciitilde{}}\FunctionTok{min}\NormalTok{(.x, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),                        }\DocumentationTok{\#\# Specified statistics}
        \AttributeTok{quartile1 =} \SpecialCharTok{\textasciitilde{}}\FunctionTok{quantile}\NormalTok{(.x, }\AttributeTok{probs =} \FloatTok{0.25}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
        \AttributeTok{quartile2 =} \SpecialCharTok{\textasciitilde{}}\FunctionTok{quantile}\NormalTok{(.x, }\AttributeTok{probs =} \FloatTok{0.50}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
        \AttributeTok{quartile3 =} \SpecialCharTok{\textasciitilde{}}\FunctionTok{quantile}\NormalTok{(.x, }\AttributeTok{probs =} \FloatTok{0.75}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
        \AttributeTok{max =} \SpecialCharTok{\textasciitilde{}}\FunctionTok{max}\NormalTok{(.x, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
        \AttributeTok{median =} \SpecialCharTok{\textasciitilde{}}\FunctionTok{median}\NormalTok{(.x, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
        \AttributeTok{meanArithmetic =} \SpecialCharTok{\textasciitilde{}}\FunctionTok{mean}\NormalTok{(.x, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
        \AttributeTok{meanStanDev =} \SpecialCharTok{\textasciitilde{}}\FunctionTok{sd}\NormalTok{(.x, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{      )}
\NormalTok{    ),}
    \AttributeTok{count =} \FunctionTok{n}\NormalTok{()                                                  }\DocumentationTok{\#\# Display the count for each Cut classification}
\NormalTok{  )}
\CommentTok{\#Diamonds Dataset Lengths contains some values equal to zero. These were not included in the data shown above}
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#}
\DocumentationTok{\#\#Polishing\#\#}
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#}

\DocumentationTok{\#\# Clean up the column names because they look rough otherwise}
\FunctionTok{colnames}\NormalTok{(dimensionStats) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Cut"}\NormalTok{, }\StringTok{"Color"}\NormalTok{, }\StringTok{"Minimum"}\NormalTok{, }\StringTok{"1st Quartile"}\NormalTok{, }\StringTok{"2nd Quartile"}\NormalTok{, }\StringTok{"3rd Quartile"}\NormalTok{, }\StringTok{"Maximum"}\NormalTok{, }\StringTok{"Median"}\NormalTok{, }\StringTok{"Mean"}\NormalTok{, }\StringTok{"Standard Deviation"}\NormalTok{, }\StringTok{"Count"}\NormalTok{)}
\DocumentationTok{\#\# Round the table with mutate, across and where}
\NormalTok{dimensionStatsRounded }\OtherTok{\textless{}{-}}\NormalTok{ dimensionStats }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\FunctionTok{across}\NormalTok{(}\FunctionTok{where}\NormalTok{(is.numeric), }\SpecialCharTok{\textasciitilde{}}\FunctionTok{round}\NormalTok{(., }\DecValTok{2}\NormalTok{)))}

\DocumentationTok{\#\# Making the table look good}
\NormalTok{dimensionStatsFormatted }\OtherTok{\textless{}{-}}\NormalTok{ dimensionStatsRounded }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable}\NormalTok{(}
    \AttributeTok{caption =} \StringTok{"Fig. 3: Statistical Facts for Diamond Length Values, in Millimeters"}\NormalTok{,}
    \AttributeTok{booktabs =} \ConstantTok{TRUE}\NormalTok{,}
    \AttributeTok{align =} \FunctionTok{c}\NormalTok{(}\StringTok{"l"}\NormalTok{, }\FunctionTok{rep}\NormalTok{(}\StringTok{"c"}\NormalTok{, }\DecValTok{6}\NormalTok{)),}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{kable\_styling}\NormalTok{(}
    \AttributeTok{full\_width =}\NormalTok{ F,}
    \AttributeTok{bootstrap\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"condensed"}\NormalTok{, }\StringTok{"responsive"}\NormalTok{),}
    \AttributeTok{font\_size =} \DecValTok{16}\NormalTok{,}
    \AttributeTok{latex\_options =} \StringTok{"scale\_down"}\NormalTok{,}
    \AttributeTok{position =} \StringTok{"center"}\NormalTok{,}
    
\NormalTok{  )}\SpecialCharTok{\%\textgreater{}\%} \DocumentationTok{\#\# Coloring the rows and font}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{row\_spec}\NormalTok{(}\DecValTok{0}\NormalTok{, }\AttributeTok{bold =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \DocumentationTok{\#\# Highlighting the most desirable combinations of Color and Cut}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{row\_spec}\NormalTok{(}\DecValTok{1}\NormalTok{, }\AttributeTok{bold =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{row\_spec}\NormalTok{(}\DecValTok{8}\NormalTok{, }\AttributeTok{bold =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{row\_spec}\NormalTok{(}\DecValTok{15}\NormalTok{, }\AttributeTok{bold =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{row\_spec}\NormalTok{(}\DecValTok{22}\NormalTok{, }\AttributeTok{bold =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{  kableExtra}\SpecialCharTok{::}\FunctionTok{row\_spec}\NormalTok{(}\DecValTok{29}\NormalTok{, }\AttributeTok{bold =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{color =} \StringTok{"black"}\NormalTok{)}

  
\DocumentationTok{\#\# Adding footnotes}
\NormalTok{dimensionStatsFormatted }\OtherTok{\textless{}{-}}\NormalTok{ dimensionStatsFormatted }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{footnote}\NormalTok{(}
    \FunctionTok{c}\NormalTok{(}\StringTok{"GGplot2 Diamonds Dataset had cases with non{-}positive Lengths. Above data excludes those."}\NormalTok{),}
    \FunctionTok{c}\NormalTok{(}\StringTok{"Data displayed above rounded to two decimal places."}\NormalTok{),}
\NormalTok{  )}
\NormalTok{dimensionStatsFormatted}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tab:codeAppendix}Fig. 3: Statistical Facts for Diamond Length Values, in Millimeters}
\centering
\resizebox{\linewidth}{!}{
\fontsize{16}{18}\selectfont
\begin{tabular}[t]{lcccccclccc}
\toprule
\textcolor{black}{\textbf{Cut}} & \textcolor{black}{\textbf{Color}} & \textcolor{black}{\textbf{Minimum}} & \textcolor{black}{\textbf{1st Quartile}} & \textcolor{black}{\textbf{2nd Quartile}} & \textcolor{black}{\textbf{3rd Quartile}} & \textcolor{black}{\textbf{Maximum}} & \textcolor{black}{\textbf{Median}} & \textcolor{black}{\textbf{Mean}} & \textcolor{black}{\textbf{Standard Deviation}} & \textcolor{black}{\textbf{Count}}\\
\midrule
\textcolor{black}{\textbf{Fair}} & \textcolor{black}{\textbf{D}} & \textcolor{black}{\textbf{4.09}} & \textcolor{black}{\textbf{5.59}} & \textcolor{black}{\textbf{6.08}} & \textcolor{black}{\textbf{6.30}} & \textcolor{black}{\textbf{9.42}} & \textcolor{black}{\textbf{6.08}} & \textcolor{black}{\textbf{6.02}} & \textcolor{black}{\textbf{0.83}} & \textcolor{black}{\textbf{163}}\\
Fair & E & 3.87 & 5.28 & 6.07 & 6.35 & 8.16 & 6.07 & 5.91 & 0.83 & 224\\
Fair & F & 4.19 & 5.45 & 6.06 & 6.37 & 8.58 & 6.06 & 5.99 & 0.88 & 312\\
Fair & G & 3.87 & 5.59 & 6.13 & 6.52 & 8.75 & 6.13 & 6.19 & 0.93 & 313\\
Fair & H & 4.40 & 6.01 & 6.33 & 7.16 & 10.00 & 6.33 & 6.58 & 0.94 & 303\\
\addlinespace
Fair & I & 4.62 & 5.92 & 6.34 & 7.14 & 9.11 & 6.34 & 6.56 & 0.90 & 175\\
Fair & J & 4.24 & 6.06 & 6.49 & 7.38 & 10.74 & 6.49 & 6.75 & 1.09 & 119\\
\textcolor{black}{\textbf{Good}} & \textcolor{black}{\textbf{D}} & \textcolor{black}{\textbf{3.83}} & \textcolor{black}{\textbf{4.78}} & \textcolor{black}{\textbf{5.69}} & \textcolor{black}{\textbf{6.31}} & \textcolor{black}{\textbf{8.15}} & \textcolor{black}{\textbf{5.69}} & \textcolor{black}{\textbf{5.62}} & \textcolor{black}{\textbf{0.93}} & \textcolor{black}{\textbf{662}}\\
Good & E & 3.83 & 4.78 & 5.68 & 6.31 & 9.08 & 5.68 & 5.62 & 0.95 & 933\\
Good & F & 3.83 & 5.02 & 5.76 & 6.32 & 8.69 & 5.76 & 5.71 & 0.92 & 907\\
\addlinespace
Good & G & 3.94 & 5.05 & 6.05 & 6.38 & 8.90 & 6.05 & 5.85 & 1.02 & 871\\
Good & H & 4.04 & 5.07 & 6.11 & 6.62 & 9.44 & 6.11 & 5.97 & 1.13 & 702\\
Good & I & 4.19 & 5.56 & 6.28 & 7.21 & 9.38 & 6.28 & 6.25 & 1.22 & 522\\
Good & J & 4.22 & 5.65 & 6.44 & 7.23 & 9.32 & 6.44 & 6.38 & 1.12 & 307\\
\textcolor{black}{\textbf{Ideal}} & \textcolor{black}{\textbf{D}} & \textcolor{black}{\textbf{3.81}} & \textcolor{black}{\textbf{4.47}} & \textcolor{black}{\textbf{5.11}} & \textcolor{black}{\textbf{5.72}} & \textcolor{black}{\textbf{9.04}} & \textcolor{black}{\textbf{5.11}} & \textcolor{black}{\textbf{5.19}} & \textcolor{black}{\textbf{0.82}} & \textcolor{black}{\textbf{2834}}\\
\addlinespace
Ideal & E & 3.76 & 4.47 & 5.10 & 5.76 & 8.52 & 5.10 & 5.22 & 0.85 & 3903\\
Ideal & F & 3.90 & 4.53 & 5.23 & 6.18 & 8.67 & 5.23 & 5.41 & 0.98 & 3825\\
Ideal & G & 3.92 & 4.52 & 5.24 & 6.49 & 8.75 & 5.24 & 5.51 & 1.04 & 4883\\
Ideal & H & 3.94 & 4.57 & 5.68 & 6.68 & 9.65 & 5.68 & 5.73 & 1.17 & 3115\\
Ideal & I & 3.94 & 4.77 & 5.84 & 6.87 & 9.49 & 5.84 & 5.98 & 1.24 & 2093\\
\addlinespace
Ideal & J & 3.93 & 5.23 & 6.50 & 7.20 & 9.25 & 6.50 & 6.32 & 1.22 & 896\\
\textcolor{black}{\textbf{Premium}} & \textcolor{black}{\textbf{D}} & \textcolor{black}{\textbf{3.73}} & \textcolor{black}{\textbf{4.71}} & \textcolor{black}{\textbf{5.38}} & \textcolor{black}{\textbf{6.44}} & \textcolor{black}{\textbf{8.99}} & \textcolor{black}{\textbf{5.38}} & \textcolor{black}{\textbf{5.60}} & \textcolor{black}{\textbf{1.02}} & \textcolor{black}{\textbf{1602}}\\
Premium & E & 3.79 & 4.70 & 5.41 & 6.41 & 9.26 & 5.41 & 5.59 & 1.03 & 2337\\
Premium & F & 3.73 & 4.87 & 5.89 & 6.55 & 9.24 & 5.89 & 5.88 & 1.02 & 2331\\
Premium & G & 3.95 & 4.75 & 5.90 & 6.71 & 9.44 & 5.90 & 5.86 & 1.15 & 2924\\
\addlinespace
Premium & H & 3.96 & 5.17 & 6.48 & 7.04 & 9.44 & 6.48 & 6.25 & 1.22 & 2359\\
Premium & I & 3.97 & 5.40 & 6.74 & 7.46 & 10.14 & 6.74 & 6.49 & 1.32 & 1428\\
Premium & J & 4.22 & 6.04 & 6.92 & 7.62 & 10.02 & 6.92 & 6.81 & 1.22 & 808\\
\textcolor{black}{\textbf{Very Good}} & \textcolor{black}{\textbf{D}} & \textcolor{black}{\textbf{3.86}} & \textcolor{black}{\textbf{4.69}} & \textcolor{black}{\textbf{5.46}} & \textcolor{black}{\textbf{6.30}} & \textcolor{black}{\textbf{9.08}} & \textcolor{black}{\textbf{5.46}} & \textcolor{black}{\textbf{5.50}} & \textcolor{black}{\textbf{0.97}} & \textcolor{black}{\textbf{1513}}\\
Very Good & E & 3.74 & 4.60 & 5.33 & 6.27 & 8.65 & 5.33 & 5.43 & 1.00 & 2400\\
\addlinespace
Very Good & F & 3.84 & 4.73 & 5.69 & 6.38 & 8.64 & 5.69 & 5.61 & 1.00 & 2164\\
Very Good & G & 3.88 & 4.69 & 5.68 & 6.44 & 8.65 & 5.68 & 5.66 & 1.04 & 2299\\
Very Good & H & 3.89 & 4.96 & 6.13 & 6.76 & 9.23 & 6.13 & 5.99 & 1.15 & 1823\\
Very Good & I & 3.95 & 5.58 & 6.35 & 7.19 & 10.01 & 6.35 & 6.27 & 1.17 & 1204\\
Very Good & J & 3.94 & 5.67 & 6.56 & 7.29 & 8.89 & 6.56 & 6.46 & 1.14 & 678\\
\bottomrule
\multicolumn{11}{l}{\rule{0pt}{1em}\textit{Note: }}\\
\multicolumn{11}{l}{\rule{0pt}{1em}GGplot2 Diamonds Dataset had cases with non-positive Lengths. Above data excludes those.}\\
\multicolumn{11}{l}{\rule{0pt}{1em}\textsuperscript{1} Data displayed above rounded to two decimal places.}\\
\end{tabular}}
\end{table}

\end{document}
